-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfzfI2csLIvdPRueb
tNODHxhR/8rnrAVWL0OHChQiWuugCgYIKoZIzj0DAQehRANCAASYjBUEFYoJIi4N
njtkb7k6atr2ybShpsyXNTrOzxl9JLkkmioB0uEighTbi6E1GF9Tbt7Rui9HpP1Z
j/7TSxT1
-----END PRIVATE KEY-----